language: python
python:
    - "2.7"
install:
    - pip install -U platformio
    - platformio upgrade --dev
script:
    - platformio run -e uno
    - platformio run -e due
    - platformio run -e esp32